### ISSUE TITLE
object Object in example

### ISSUE THREAD

**Issue by AlexHolly** [raml-org/raml-java-parser-2#13]
IN

```
...
types:

  Users:
    type:
      - object
    properties:
      users: string[]
    example:
      users: [name1, name2]
...
```

OUT

``` "
...
types" : [ {
            "properties" : [ {
                    "name" : "users",
                    "type" : [
                        "string[]"
                    ]
                }
            ],
            "example" : "[object Object]",
            "name" : "Users",
            "type" : [
                "object"
            ]
        }
...

```

I expect on "[object Object]" some example names "["name1", "name2"]"

Is this a bug?
